//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XBuilder.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        internal static byte[] Cube {
            get {
                object obj = ResourceManager.GetObject("Cube", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CubeTexture {
            get {
                object obj = ResourceManager.GetObject("CubeTexture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cylinder {
            get {
                object obj = ResourceManager.GetObject("Cylinder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content pipeline add-in store returned the following error:
        ///{0}
        ///The XNA Framework Content Pipeline properties will not be editable unless the problem is fixed..
        /// </summary>
        internal static string PipelineAddInInvalidPipeline {
            get {
                return ResourceManager.GetString("PipelineAddInInvalidPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XNA Framework version &apos;{0}&apos; is not supported by this installation of XNA Game Studio, or a required component is missing..
        /// </summary>
        internal static string PipelineAddInInvalidVersion {
            get {
                return ResourceManager.GetString("PipelineAddInInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content project does not contain an XnaFrameworkVersion property. The XNA Framework Content Pipeline properties will be disabled..
        /// </summary>
        internal static string PipelineAddInMissingVersionProperty {
            get {
                return ResourceManager.GetString("PipelineAddInMissingVersionProperty", resourceCulture);
            }
        }
        
        internal static byte[] Plane {
            get {
                object obj = ResourceManager.GetObject("Plane", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Sphere {
            get {
                object obj = ResourceManager.GetObject("Sphere", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Teapot {
            get {
                object obj = ResourceManager.GetObject("Teapot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Preview.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        internal static byte[] Torus {
            get {
                object obj = ResourceManager.GetObject("Torus", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
